import React from 'react';
import { Icon } from '../components/index.js';
import { DATENSCHUTZ_HINWEIS } from '../data/content.js';
import { CONTENT_REPO_URL } from '../lib/links.js';
import { clearDraft, readDraft, writeDraft } from '../lib/contributionDraft.js';
import { buildAp14IssueDraft } from '../lib/ap14Handoff.js';
import { emptyAnswers, fieldsForType, slug, TYPES } from '../lib/contribution/model.js';
import { validateForm } from '../lib/contribution/validateForm.js';
import { buildFiles } from '../lib/contribution/generate.js';
import { validatePackage } from '../lib/contribution/validate.js';
import { buildZip, downloadZip, safeName } from '../lib/contribution/zip.js';

const STEPS = ['Überblick & Typ wählen', 'Grunddaten', 'Inhalt', 'Szenario-Triade & Grenzen', 'Quellen, Lizenz & Datenschutz', 'Prüfung & Vorschau', 'Einreichen'];
const TEXT_EXTENSIONS = ['md', 'txt', 'yml', 'yaml', 'json'];
const BINARY_EXTENSIONS = ['pdf', 'docx'];

export default function Contribution() {
  const [active, setActive] = React.useState(0); const [selectedType, setSelectedType] = React.useState('prompt');
  const [answers, setAnswers] = React.useState(() => emptyAnswers('prompt'));
  const [acknowledgements, setAcknowledgements] = React.useState({ public_content_confirmed: false, no_real_personal_data_confirmed: false, pii_hints_reviewed: false });
  const [attachments, setAttachments] = React.useState([]); const [persist, setPersist] = React.useState(false); const [notice, setNotice] = React.useState(''); const [hydrated, setHydrated] = React.useState(false);
  React.useEffect(() => { const draft = readDraft(); if (draft?.v === 2 && TYPES[draft.selectedType]) { setActive(Math.min(6, Number(draft.step) || 0)); setSelectedType(draft.selectedType); setAnswers({ ...emptyAnswers(draft.selectedType), ...draft.answers }); setAcknowledgements((current) => ({ ...current, ...draft.acknowledgements })); setPersist(true); } setHydrated(true); }, []);
  React.useEffect(() => { if (hydrated && persist) writeDraft({ v: 2, step: active, selectedType, answers, acknowledgements }); }, [active, selectedType, answers, acknowledgements, persist, hydrated]);
  const files = buildFiles({ type: selectedType, answers });
  const formErrors = validateForm(selectedType, answers, acknowledgements);
  const packageResult = validatePackage(files, { ...answers, artifact_type: TYPES[selectedType].artifactType, status: 'draft', human_review_required: true }, selectedType);
  const allErrors = [...formErrors, ...packageResult.errors];
  const update = (key, value) => setAnswers((current) => { const next = { ...current, [key]: value }; if (key === 'title' && (!current.id || current.id === slug(current.title))) next.id = slug(value); return next; });
  const setType = (type) => { setSelectedType(type); setAnswers(emptyAnswers(type)); setAttachments([]); setNotice(''); };
  const reset = () => { clearDraft(); setPersist(false); setActive(0); setSelectedType('prompt'); setAnswers(emptyAnswers('prompt')); setAcknowledgements({ public_content_confirmed: false, no_real_personal_data_confirmed: false, pii_hints_reviewed: false }); setAttachments([]); setNotice(''); };
  const chooseFiles = async (event, field) => { const chosen = Array.from(event.target.files || []); event.target.value = ''; const total = attachments.reduce((sum, file) => sum + file.size, 0) + chosen.reduce((sum, file) => sum + file.size, 0); if (attachments.length + chosen.length > 25 || total > 25 * 1024 * 1024) { setNotice('Maximal 25 Dateien bzw. 25 MB sind erlaubt.'); return; } for (const file of chosen) { const extension = file.name.split('.').pop()?.toLowerCase(); if (TEXT_EXTENSIONS.includes(extension)) { try { update(field, await file.text()); setNotice(`„${file.name}“ wurde lokal in das Feld übernommen.`); } catch { setNotice(`„${file.name}“ konnte nicht als Text gelesen werden.`); } } else if (BINARY_EXTENSIONS.includes(extension)) { setAttachments((current) => [...current, file]); setNotice(`„${file.name}“ bleibt lokal und wird nur dem ZIP hinzugefügt.`); } else setNotice(`„${file.name}“ ist nicht erlaubt.`); } };
  const makeZip = async () => { if (allErrors.length) { setActive(5); setNotice('Bitte behebe zuerst die angezeigten Fehler.'); return; } const binary = await Promise.all(attachments.map(async (file) => ({ path: `${TYPES[selectedType].folder}/${answers.id}/attachments/${safeName(file.name)}`, binary: await file.arrayBuffer() }))); downloadZip(await buildZip([...files, ...binary]), `kitomat-${selectedType}-${answers.id}.zip`); setNotice('ZIP wurde lokal erstellt. Es wurden keine Dateien hochgeladen.'); };
  const issue = () => { if (allErrors.length || attachments.length) { setActive(5); setNotice(attachments.length ? 'Mit Binäranhängen ist nur der ZIP-Weg möglich.' : 'Bitte behebe zuerst die angezeigten Fehler.'); return; } try { const draft = buildAp14IssueDraft({ selectedType, answers, acknowledgements }); const url = `${CONTENT_REPO_URL}/issues/new?title=${encodeURIComponent(draft.title)}&body=${encodeURIComponent(draft.body)}`; if (url.length <= 6000) window.open(url, '_blank', 'noopener,noreferrer'); else navigator.clipboard?.writeText(draft.body).then(() => setNotice('Payload kopiert: bitte in ein neues GitHub-Issue einfügen.')); } catch (error) { setNotice(error.message); } };
  const typeFields = fieldsForType(selectedType); const trustKeys = new Set(['license', 'license_status', 'data_risk', 'ai_act_proximity', 'sources_status']); const basics = typeFields.filter((field) => ['title', 'id', 'category', 'language', 'maintainer'].includes(field.key)); const content = typeFields.filter((field) => !trustKeys.has(field.key) && !basics.includes(field) && !field.key.startsWith('scenario_') && field.key !== 'failure_modes'); const scenarios = typeFields.filter((field) => field.key.startsWith('scenario_') || field.key === 'failure_modes'); const trust = typeFields.filter((field) => trustKeys.has(field.key));
  return <main className="page"><div className="container contribution-page"><div className="contribution-heading"><div><div className="h-eyebrow">Contribution Center</div><h1 className="h2">Beitrag in sieben Schritten vorbereiten</h1><p className="muted">Echte Prüfungen und lokale Dateiübernahme. Fachliche Freigabe bleibt menschlich.</p></div><button className="btn btn-ghost btn-sm" onClick={reset}><Icon.close /> Neuer Beitrag</button></div><div className="card contribution-privacy"><strong>Datenschutz vor dem Start</strong><span>{DATENSCHUTZ_HINWEIS} Textdateien werden lokal gelesen. Erst beim GitHub-Issue werden ausdrücklich übergebene Texte öffentlich; PDF/DOCX bleiben im lokalen ZIP.</span></div><label className="contribution-persist"><input type="checkbox" checked={persist} onChange={(event) => { setPersist(event.target.checked); if (!event.target.checked) clearDraft(); }} /> Entwurf nur in diesem Browser-Tab speichern (keine Binäranhänge)</label><div className="contribution-layout"><aside className="card contribution-steps">{STEPS.map((title, index) => <button key={title} className={`stepper-step ${active === index ? 'active' : ''} ${index < active ? 'done' : ''}`} onClick={() => setActive(index)}><span className="step-num">{index + 1}</span><span>{title}</span></button>)}</aside><section className="card contribution-content"><div className="mono contribution-step-label">SCHRITT {active + 1} / 7</div><h2 className="h2">{STEPS[active]}</h2>{active === 0 && <TypeStep selectedType={selectedType} setType={setType} />}{active === 1 && <FieldGroup fields={basics} answers={answers} update={update} chooseFiles={chooseFiles} />}{active === 2 && <><p className="muted">Textdateien füllen das gewählte Feld lokal aus. PDF/DOCX werden ausschließlich als ZIP-Anhang vorgemerkt.</p><FieldGroup fields={content} answers={answers} update={update} chooseFiles={chooseFiles} /><AttachmentList attachments={attachments} remove={(file) => setAttachments((current) => current.filter((item) => item !== file))} /></>}{active === 3 && <FieldGroup fields={scenarios} answers={answers} update={update} chooseFiles={chooseFiles} />}{active === 4 && <><FieldGroup fields={trust} answers={answers} update={update} chooseFiles={chooseFiles} /><Acknowledgements acknowledgements={acknowledgements} setAcknowledgements={setAcknowledgements} /></>}{active === 5 && <CheckStep errors={allErrors} hints={packageResult.hints} files={files} />}{active === 6 && <SubmitStep attachments={attachments.length} makeZip={makeZip} issue={issue} />}{notice && <div className="contribution-notice" role="status">{notice}</div>}<div className="contribution-nav"><button className="btn btn-ghost" disabled={!active} onClick={() => setActive((value) => value - 1)}>Zurück</button>{active < 6 && <button className="btn btn-primary" onClick={() => setActive((value) => value + 1)}>Weiter <Icon.arrow /></button>}</div></section></div></div></main>;
}
function TypeStep({ selectedType, setType }) { return <div className="contribution-types">{Object.entries(TYPES).map(([id, type]) => <button key={id} className={`card ${id === selectedType ? 'contribution-type-active' : ''}`} onClick={() => setType(id)}><strong>{type.label}</strong><span>{id === 'prompt' ? 'Prompt mit Beispielen und Grenzen.' : id === 'dataset' ? 'Quellen mit Herkunft und Lizenz.' : 'Modell für Branche oder Organisation.'}</span></button>)}</div>; }
function FieldGroup({ fields, answers, update, chooseFiles }) { return <div className="contribution-fields">{fields.map((field) => <FieldRow key={field.key} field={field} value={answers[field.key]} update={update} chooseFiles={chooseFiles} />)}</div>; }
function FieldRow({ field, value, update, chooseFiles }) { const id = `field-${field.key}`; const text = field.kind === 'list' ? (value || []).join('\n') : value || ''; return <label className="contribution-field" htmlFor={id}><span><strong>{field.label}</strong>{field.required ? ' *' : ''}</span>{field.kind === 'select' ? <select id={id} value={text} onChange={(event) => update(field.key, event.target.value)}>{field.options.map((option) => <option key={option} value={option}>{option}</option>)}</select> : field.kind === 'boolean' ? <select id={id} value={String(value)} onChange={(event) => update(field.key, event.target.value === 'true')}><option value="false">Nein</option><option value="true">Ja</option></select> : <textarea id={id} rows={field.kind === 'longtext' || field.kind === 'list' ? 5 : 2} value={text} onChange={(event) => update(field.key, field.kind === 'list' ? event.target.value.split('\n').map((item) => item.trim()).filter(Boolean) : event.target.value)} />}{['text', 'longtext'].includes(field.kind) && <span className="contribution-file-input"><input aria-label={`${field.label} aus Datei übernehmen`} type="file" accept=".md,.txt,.yml,.yaml,.json,.pdf,.docx" onChange={(event) => chooseFiles(event, field.key)} />Datei lokal übernehmen (PDF/DOCX: ZIP-Anhang)</span>}</label>; }
function AttachmentList({ attachments, remove }) { return attachments.length ? <div className="contribution-attachments"><strong>Lokale ZIP-Anhänge</strong>{attachments.map((file) => <div key={`${file.name}-${file.lastModified}`}><span>{file.name} · {Math.ceil(file.size / 1024)} KB</span><button className="btn btn-ghost btn-sm" onClick={() => remove(file)}>Entfernen</button></div>)}</div> : null; }
function Acknowledgements({ acknowledgements, setAcknowledgements }) { const items = [['public_content_confirmed', 'Mir ist klar, dass per GitHub-Issue übergebene Textinhalte öffentlich werden.'], ['no_real_personal_data_confirmed', 'Ich bestätige, dass keine echten Personen-, Kunden-, Gesundheits-, HR- oder vertraulichen Finanzdaten enthalten sind.'], ['pii_hints_reviewed', 'Ich habe mögliche PII-Hinweise geprüft und nur zulässige Inhalte belassen.']]; return <div className="contribution-checks"><p>Diese Angaben sind eine Selbstauskunft und keine automatische Trust-Freigabe.</p>{items.map(([key, label]) => <label key={key}><input type="checkbox" checked={acknowledgements[key]} onChange={(event) => setAcknowledgements((current) => ({ ...current, [key]: event.target.checked }))} /> {label}</label>)}</div>; }
function CheckStep({ errors, hints, files }) { return <div><div className={`contribution-check-result ${errors.length ? 'is-error' : 'is-ok'}`}><strong>{errors.length ? `${errors.length} Angaben müssen noch korrigiert werden.` : 'Technische und formale Prüfung bestanden.'}</strong><span>{errors.length ? 'Die fachliche Prüfung erfolgt erst im Pull Request.' : 'Die inhaltliche Prüfung erfolgt nach der Einreichung im Pull Request durch Review-Assistent und Menschen.'}</span></div>{errors.map((item, index) => <div className="contribution-finding" key={`${item.field}-${index}`}>Ebene {item.ebene}: {item.message}</div>)}{hints.map((item, index) => <div className="contribution-finding contribution-hint" key={`${item.code}-${index}`}>Hinweis: {item.message}</div>)}<details><summary>Erzeugte Dateien ({files.length})</summary><ul>{files.map((file) => <li key={file.path}><code>{file.path}</code></li>)}</ul></details></div>; }
function SubmitStep({ attachments, makeZip, issue }) { return <div className="contribution-submit"><div className="card"><h3>Weg A: In GitHub einreichen</h3><p>Für reine Textbeiträge: Issue absenden, Maintainer-Freigabe abwarten, dann entstehen Branch und Pull Request. {attachments ? 'Mit Binäranhängen ist dieser Weg gesperrt.' : ''}</p><button className="btn btn-primary" onClick={issue} disabled={Boolean(attachments)}>GitHub-Issue vorbereiten</button></div><div className="card"><h3>Weg B: ZIP herunterladen</h3><p>ZIP entpacken, Repository forken, Branch erstellen, Dateien hochladen und Pull Request öffnen.</p><button className="btn btn-secondary" onClick={makeZip}>ZIP herunterladen</button></div></div>; }
